Setup and mobile first
danielf-canon/Portfolio pull request #1
Opened 2023-05-04 20:09 UTC by danielf-canon

First two sections: toolbar with a burger menu and headline section with flexbox.

2023-05-04 20:59 UTC, NatiG25 reviewed
## :red_circle: INVALID PULL REQUEST :red_circle: 

## Hi @danielf-canon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>
:x: Didn't have proper README:
- Didn't remove Microverse Template.
- Not having an MIT license. 
- Not including all main headers from the [REAMDE template](https://github.com/microverseinc/readme-template) 
- Having a Live Demo section without having a deployed project. Since it's not mandatory to have your project deployed, kindly, remove it.
- Not removing the section description, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed.

![Screenshot from 2023-05-04 23-56-18](https://user-images.githubusercontent.com/86069740/236327528-a978e3c7-bf3f-4de7-a748-87dbf2ec0337.png)

:x: Not having a proper PR description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-04 23:56 UTC, Johnadibe reviewed
Hi @danielf-canon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has a broken MIT License link in your README file. To address this issue, I would recommend creating a LICENSE.md file in your repository and also include the license header at the top of the file. Then, you can copy the text of the MIT License into this file.👍

![license](https://user-images.githubusercontent.com/40009354/236353740-b557af8f-408d-44a7-9257-ca76eeed1f6b.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 03:21 UTC, stanleySimeon requested changes
# Hi @danielf-canon 
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

# Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 03:21 UTC, stanleySimeon commented on index.html
> +        </ul>
Kindly I suggest you remove the menu list in the mobile version of your design, it should appear only in the desktop version

>### Your design
>
>
<img width="366" alt="Screenshot 2023-05-05 at 11 12 58 PM" src="https://user-images.githubusercontent.com/91237525/236595848-f201a1a8-be06-4b6d-8cad-40fa5eed93ff.png">

2023-05-06 03:21 UTC, stanleySimeon commented on index.html
> +      </div>
Kindly you should stick to the design as much as possible using the same (font, margin, padding, colors, etc.), I suggest you use the same font in the Figma design.

>### Your design
>
><img width="363" alt="Screenshot 2023-05-05 at 11 18 35 PM" src="https://user-images.githubusercontent.com/91237525/236596085-02348192-104c-4064-afd8-c6539d346ccb.png">
>
>### The Figma design
>
><img width="186" alt="Screenshot 2023-05-05 at 11 19 34 PM" src="https://user-images.githubusercontent.com/91237525/236596124-cc321299-4e0b-4c7f-8b42-ea4c64c7bb4c.png">
>
>### Kindly make sure you follow the Figma template and make sure you use the correct layout before asking for another review

2023-05-06 12:18 UTC, emmiiorji requested changes
Hi @danielf-canon, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871494-508d17d2-994a-4882-9dbe-dc118efcad37.gif'/>
</div>

 ## Good Highlights✔️

- Good use of background image to represent non-content image
- Good documentation in readme


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 12:18 UTC, emmiiorji commented on style.css
> +}
You have done great by removing the menu items on mobile version, kindly adjust the background image not to overlap with the hamburger image.

Your design:
![image](https://user-images.githubusercontent.com/20554583/236623528-b2fa2f2e-9755-4fdc-9346-27ca3ab49b43.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/236623537-614d2e9e-451c-4e8c-8bfc-6c035423f23f.png)

2023-05-06 12:34 UTC, Owusu-Desmond approved these changes
Hi @danielf-canon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/qx8pi39Lwm9Xm2audb/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Nice UI✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 21:17 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @danielf-canon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 21:15 UTC, merged