JS changes
danielf-canon/Portfolio pull request #13
Opened 2023-07-06 20:21 UTC by danielf-canon

In this current branch these are some of the features recently added:

The hamburger menu with javascript.
Animations to the hamburger menu.
Refactoring the structure of the portfolio.

2023-07-06 20:47 UTC, skyv26 requested changes
## Hi @danielf-canon, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Linters are green ✅ 

## Required Changes ♻️

- [ ] Because I am not able to make an inline comment on your `README` file, as it is not visible in file changes. So that's why I am asking for changes for your `README` file here related to **MIT** license. Please make a separate file with either `MIT.md` or `LICENSE` name and paste the content of license which your directly put it on the `README` under the license section because, on README it looks bad. Attaching a license file, make your documentation looks more good.

### Problem

![image](https://github.com/danielf-canon/Portfolio/assets/66476329/4fff4937-2c03-42fc-a6fd-8eb4749e7621)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 20:47 UTC, skyv26 commented on index.html
- [ ] Kindly adhere to the project requirement because as I can see your design needs some UI touch-up, like your `hamburger` icons looks bigger than the actual design and you need to increase some spacing at the top of your intro section because of this UI issue your design looks `inconsistent` and unprofessional little bit. Please have a look at the below-attached image table and add the arrow button if you carefully look at the figma design, which in your case is missing.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Figma Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![image](https://github.com/danielf-canon/Portfolio/assets/66476329/964306b6-b6ba-4934-84b9-64b9aa39553e)

</td>
<td>

![image](https://github.com/danielf-canon/Portfolio/assets/66476329/c110dc01-cbea-4dd2-81a6-eb38e5056c00)

</td>
</tr>
</table>


## **NOTE**

*Please remove all other code that you have added in advance. Keep your advance feature functionality for your next milestone for code review. I would request code reviewer to take this in consideration.*

2023-07-07 00:22 UTC, Shedrack-Sunday requested changes
Hi @danielf-canon 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have the `Key features` section. Kindly add it up 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-08 14:44 UTC, Shedrack-Sunday requested changes
Hi @danielf-canon

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request 🔴
You have submitted a project that does not have the Key features section added to your README file. Kindly add it up 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

2023-07-08 14:56 UTC, topeogunleye reviewed
Hi @danielf-canon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a wrong PR from  popup-window project to be reviewed as Activity name: Portfolio: finish mobile version.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-08 15:07 UTC, souad988 approved these changes
Hi @danielf-canon  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
No linter errors 
Good Efforts

## Optional suggestions
_ Please Next time when reppeating a module submit the approved PR for each activity so the reviewers don't get confused. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 15:14 UTC, Zuhaib042 approved these changes
Hi @danielf-canon 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l0MYKO0EWhuiZQ2RO/giphy.gif)
## Highlights
✅ Nice design
✅ Implemented suggested changes nicely
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 09:12 UTC, closed without merging